#!/usr/bin/env python3
"""Sync the Chrome extension's bundled planner with site/planner/.

The extension at chrome-extension/extension/ pins its own copies of the
planner app. Those copies are the SITE files plus a small set of known
shims (absolute URLs for /api/share, /api/planner-beacon, the quote POST,
and the share-link base; local fonts + favicon in planner.html). This
script regenerates every extension copy from the current site files and
re-applies the shims via exact-match anchors — if an anchor no longer
matches exactly once, the site file changed shape and the script fails
loudly instead of silently shipping a broken transform.

Usage:
    python3 _build/sync_extension.py           # write the synced files
    python3 _build/sync_extension.py --check   # dry-run diff; exit 1 on drift

After a real sync: bump "version" in chrome-extension/extension/manifest.json,
re-zip the extension/ directory, and resubmit to the Chrome Web Store
(review usually takes days — the site can deploy ahead of it safely, the
extension keeps working on its pinned copies).
"""

import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SITE = ROOT / "site"
SITE_PLANNER = SITE / "planner"
EXT = ROOT / "chrome-extension" / "extension"
EXT_PLANNER = EXT / "planner"

# Files copied byte-for-byte from site/planner/ into extension/planner/.
VERBATIM = [
    "planner.css",
    "layout-gen.js",
    "catalog.json",
    "templates.json",
    "rentkit-map.json",
    "partners.json",
    "vendor/jspdf.umd.min.js",
    "vendor/svg2pdf.umd.min.js",
    "vendor/qrcode.min.js",
]

# planner.js shims: (site anchor, extension replacement). Every anchor must
# appear EXACTLY once in the site file.
PLANNER_JS_SHIMS = [
    (
        "'/api/planner-beacon',",
        "SITE_URL + '/api/planner-beacon',",
    ),
    (
        "      baseUrl = location.origin + '/event-layout-planner';",
        "      // Extension build: location.origin is chrome-extension://, useless in\n"
        "      // a shared link — always point recipients at the hub page.\n"
        "      baseUrl = PLANNER_HUB_URL;",
    ),
    (
        "fetch('/api/share', {",
        "fetch(SITE_URL + '/api/share', {",
    ),
    (
        "const res = await fetch('/', { method: 'POST', body: fd });",
        "const res = await fetch(SITE_URL + '/', { method: 'POST', body: fd });",
    ),
]

EMBED_HEADER = """<!-- Forever Party Rentals — Event Layout Planner (embed surface)
     This file is the bare planner app. Loaded both inside an iframe on the
     hub page (event-layout-planner.html) and on third-party sites that
     embed the tool. No nav, no footer, no GTM. Headers in site/_headers
     relax X-Frame-Options + frame-ancestors for this exact path so cross-
     origin iframing works. Excluded from sitemap.xml; canonical points to
     the hub page so search engines consolidate signals there. -->"""

EXT_HEADER = """<!-- Forever Party Rentals — Event Layout Planner (Chrome extension build)
     GENERATED by _build/sync_extension.py from site/event-layout-planner-embed.html
     — edit the site file and re-run the sync; do not hand-edit this copy.
     Differences from the web embed: fonts are bundled locally so the app
     works fully offline, and planner.js has the /api/share,
     /api/planner-beacon, and quote-POST endpoints pointed at
     https://www.foreverpartyrentals.com absolutely (host_permissions in
     manifest.json exempt those calls from CORS). -->"""

# The site head's SEO/preload block collapses to the local fonts stylesheet.
EMBED_HEAD_BLOCK = """<meta name="description" content="Drag-and-drop event layout planner from Forever Party Rentals. Plan tents, tables, chairs, dance floors and stage in 2D for your event."/>
<meta name="robots" content="noindex,follow"/>
<link rel="canonical" href="https://www.foreverpartyrentals.com/event-layout-planner"/>
<link rel="preload" as="font" type="font/woff2" href="/fonts/playfair-display-variable.woff2" crossorigin/>
<link rel="preload" as="font" type="font/woff2" href="/fonts/jost-variable.woff2" crossorigin/>"""

PLANNER_HTML_SHIMS = [
    (EMBED_HEADER, EXT_HEADER),
    (EMBED_HEAD_BLOCK, '<link rel="stylesheet" href="fonts/fonts.css"/>'),
    ('href="/favicon.svg"', 'href="favicon.svg"'),
    ('action="/thank-you"', 'action="https://www.foreverpartyrentals.com/thank-you"'),
]


def apply_shims(text: str, shims, label: str) -> str:
    for anchor, replacement in shims:
        n = text.count(anchor)
        if n != 1:
            raise SystemExit(
                f"ERROR: shim anchor matched {n}× (need exactly 1) in {label}:\n"
                f"  {anchor.splitlines()[0][:100]}\n"
                f"The site file changed shape — update PLANNER shims in "
                f"_build/sync_extension.py before syncing."
            )
        text = text.replace(anchor, replacement)
    return text


def build_outputs():
    """Return {ext_relative_path: content_bytes} for everything we manage."""
    out = {}
    for rel in VERBATIM:
        src = SITE_PLANNER / rel
        out[f"planner/{rel}"] = src.read_bytes()
    planner_js = (SITE_PLANNER / "planner.js").read_text(encoding="utf-8")
    out["planner/planner.js"] = apply_shims(
        planner_js, PLANNER_JS_SHIMS, "site/planner/planner.js"
    ).encode("utf-8")
    embed_html = (SITE / "event-layout-planner-embed.html").read_text(encoding="utf-8")
    out["planner.html"] = apply_shims(
        embed_html, PLANNER_HTML_SHIMS, "site/event-layout-planner-embed.html"
    ).encode("utf-8")
    return out


def main():
    check = "--check" in sys.argv
    outputs = build_outputs()
    drift = []
    for rel, content in outputs.items():
        dest = EXT / rel
        if not dest.exists() or dest.read_bytes() != content:
            drift.append(rel)
    if check:
        if drift:
            print("DRIFT — extension copies out of sync with site/planner/:")
            for rel in drift:
                print(f"  - chrome-extension/extension/{rel}")
            print("Run: python3 _build/sync_extension.py")
            sys.exit(1)
        print("CLEAN — extension planner matches site/planner/ + known shims.")
        return
    for rel, content in outputs.items():
        dest = EXT / rel
        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_bytes(content)
    print(f"synced {len(outputs)} files → chrome-extension/extension/ "
          f"({len(drift)} changed)")
    if drift:
        print("Next: bump manifest.json \"version\", re-zip extension/, and "
              "resubmit to the Chrome Web Store.")


if __name__ == "__main__":
    main()
