#!/usr/bin/env python3
"""
Forever Party Rentals — sync catalog prices from the live RentKit shop API.

Sources of truth
  * Live rates:  POST https://api.rentkit.com/api/embedded-shop/getShopInventory
                 (public embedded-shop endpoint, no auth; body {"orgId": ...};
                 orgId read from _build/site_constants.json "adelieOrgId").
                 Rates come back in CENTS. Each inventory item carries a
                 rates[] list ({rate, rateName, rateRange}) plus a convenience
                 dayRate object; the Daily rate is the retail price for both
                 per-day AND per-event items (verified: 20x20 marquee Daily =
                 55000 cents = the $550/event price).
  * Mapping:     _build/sku_to_adelie_id.json — products_sku key -> RentKit id
                 (bare string) or [{id, label}] for multi-size SKUs.

Targets
  * site/planner/catalog.json   — groups[].items[].priceCAD (priceUnit is
                                  authoritative here; only the number syncs)
  * _build/products_sku.json    — products.<sku>.startingPriceCAD
  * site/planner/rentkit-map.json — generated planner-key -> RentKit-id map
                                  (written in BOTH modes; needs no network)

Usage
    python3 _build/sync_planner_catalog.py --check
        Fetch live rates, print a diff table for both files, exit 1 on any
        drift / 0 when clean. Network errors soft-fail (warning + exit 0) so
        offline builds don't break.

    python3 _build/sync_planner_catalog.py --write
        Apply live prices to both files via surgical text edits (everything
        but the changed numbers is preserved byte-for-byte), print what
        changed, and remind about the ?v= cache-bust + page regeneration.

Matching rules
  * planner item.sku -> sku_to_adelie_id.json -> RentKit item id -> Daily rate.
  * Multi-size SKUs (array values): the planner label's first NxM size token
    ('12×12' normalises to '12x12') must equal the mapping entry label's first
    size token — whole-token equality, so '8x8' never matches '18x18'.
  * products_sku startingPriceCAD for multi-size SKUs: anchored to the mapped
    sub-item whose live rate is closest to the current value (tie -> cheaper),
    so the anchor is stable once synced. The chosen anchor is printed.
  * Rate 0/missing, or a mapped id absent from the live shop inventory:
    current price is kept and the row is noted — never silently zeroed.

Stdlib only (urllib.request); no jinja2, no third-party deps.
"""
from __future__ import annotations

import argparse
import json
import re
import sys
import urllib.error
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
SITE_DIR = HERE.parent / "site"

CATALOG_FILE = SITE_DIR / "planner" / "catalog.json"
MAP_OUT_FILE = SITE_DIR / "planner" / "rentkit-map.json"
PRODUCTS_SKU_FILE = HERE / "products_sku.json"
SKU_MAP_FILE = HERE / "sku_to_adelie_id.json"
CONSTANTS_FILE = HERE / "site_constants.json"

API_URL = "https://api.rentkit.com/api/embedded-shop/getShopInventory"
TIMEOUT_S = 25

# First "NxM" size token in a label; planner uses '×' (U+00D7), RentKit 'x'.
SIZE_TOKEN_RE = re.compile(r"(\d+)\s*[x×]\s*(\d+)", re.IGNORECASE)

MAP_COMMENT = (
    "Generated by _build/sync_planner_catalog.py — do not edit by hand "
    "(regenerated on every --check/--write run). Maps Event Layout Planner "
    "item keys (site/planner/catalog.json) to RentKit/Adelie inventory item "
    "ids, resolved via planner item.sku -> _build/sku_to_adelie_id.json. "
    "Single-item SKUs map to a bare id string. Multi-size SKUs (array values "
    "in sku_to_adelie_id.json) are matched by size token: the first NxM "
    "token in the planner item label (e.g. '12×12', with '×' normalised to "
    "'x') must equal the first NxM token in the mapping entry's label — "
    "whole-token equality, so '8x8' never matches '18x18'. A planner item "
    "whose sku maps to an array but whose label carries no size token gets "
    "the full array of ids. Planner items with no resolvable mapping are "
    "listed in _unmapped rather than dropped."
)


# --------------------------------------------------------------------------
# small helpers
# --------------------------------------------------------------------------

def load_json(path: Path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def size_token(label: str) -> str | None:
    """Return the first normalised 'NxM' size token in a label, or None."""
    m = SIZE_TOKEN_RE.search(label or "")
    return f"{int(m.group(1))}x{int(m.group(2))}" if m else None


def cents_to_cad(cents) -> float:
    return cents / 100.0


def fmt_price_literal(cad: float, always_decimals: bool = False) -> str:
    """Format a CAD value the way each JSON file writes prices.
    catalog.json: whole dollars bare ('750'), fractional 2dp ('13.50').
    products_sku.json (always_decimals=True): always 2dp ('750.00')."""
    if not always_decimals and float(cad).is_integer():
        return str(int(cad))
    return f"{cad:.2f}"


def day_rate_cents(item: dict | None):
    """Daily rate in cents for a live inventory item, or None.
    Prefers the convenience dayRate object, falls back to rates[]."""
    if not isinstance(item, dict):
        return None
    dr = item.get("dayRate")
    if isinstance(dr, dict) and isinstance(dr.get("rate"), (int, float)):
        return dr["rate"] or None  # treat 0 as missing
    for r in item.get("rates", []) or []:
        if r.get("rateRange") == "day" and isinstance(r.get("rate"), (int, float)):
            return r["rate"] or None
    return None


# --------------------------------------------------------------------------
# live inventory
# --------------------------------------------------------------------------

def fetch_inventory(org_id: str) -> dict[str, dict]:
    """POST getShopInventory and return {item_id: item}. Raises on any
    network / HTTP / shape problem; callers decide soft vs hard failure."""
    body = json.dumps({"orgId": org_id}).encode("utf-8")
    req = urllib.request.Request(
        API_URL,
        data=body,
        headers={
            "Content-Type": "application/json",
            "User-Agent": "fpr-build-price-sync/1.0",
        },
        method="POST",
    )
    with urllib.request.urlopen(req, timeout=TIMEOUT_S) as resp:
        data = json.loads(resp.read().decode("utf-8"))
    # Response shape: {"status": "ok", "items": [...]} (list fallback kept
    # for schema-drift resilience, mirroring the RentKit client contract).
    items = data.get("items", data) if isinstance(data, dict) else data
    if not isinstance(items, list) or not items:
        raise RuntimeError(f"unexpected/empty inventory response: {str(data)[:200]}")
    return {it["id"]: it for it in items if isinstance(it, dict) and it.get("id")}


# --------------------------------------------------------------------------
# planner item -> RentKit id resolution + rentkit-map.json
# --------------------------------------------------------------------------

def resolve_planner_items(catalog: dict, sku_map: dict):
    """Return (resolved, unmapped):
      resolved: {planner_key: id-string | [id, ...]} in catalog order
      unmapped: [planner_key, ...] for items with no resolvable mapping."""
    resolved: dict[str, str | list[str]] = {}
    unmapped: list[str] = []
    for group in catalog.get("groups", []):
        for item in group.get("items", []):
            key = item["key"]
            entry = sku_map.get(item.get("sku") or "")
            if isinstance(entry, str):
                resolved[key] = entry
            elif isinstance(entry, list):
                tok = size_token(item.get("label", ""))
                if tok is None:
                    # No size token to disambiguate — surface every id.
                    resolved[key] = [e["id"] for e in entry if e.get("id")]
                    continue
                hits = [e for e in entry
                        if e.get("id") and size_token(e.get("label", "")) == tok]
                if len(hits) == 1:
                    resolved[key] = hits[0]["id"]
                else:
                    unmapped.append(key)
            else:
                unmapped.append(key)
    return resolved, unmapped


def write_rentkit_map(resolved: dict, unmapped: list[str]) -> None:
    out: dict = {"_comment": MAP_COMMENT}
    out.update(resolved)
    out["_unmapped"] = unmapped
    MAP_OUT_FILE.write_text(
        json.dumps(out, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )


# --------------------------------------------------------------------------
# diff rows
# --------------------------------------------------------------------------

def build_catalog_rows(catalog: dict, resolved: dict, inventory: dict) -> list[dict]:
    """One row per planner item that resolved to a single RentKit id."""
    rows = []
    for group in catalog.get("groups", []):
        for item in group.get("items", []):
            key = item["key"]
            target = resolved.get(key)
            if target is None:
                continue  # unmapped — reported separately
            row = {
                "key": key,
                "unit": item.get("priceUnit", "?"),
                "current": float(item["priceCAD"]),
                "live": None,
                "status": "ok",
                "note": "",
            }
            if isinstance(target, list):
                row["status"] = "skipped"
                row["note"] = "multi-item mapping, no size token — not synced"
                rows.append(row)
                continue
            if target not in inventory:
                row["status"] = "no-rate"
                row["note"] = "id not in live shop inventory — price kept"
                rows.append(row)
                continue
            cents = day_rate_cents(inventory[target])
            if cents is None:
                row["status"] = "no-rate"
                row["note"] = "no/zero daily rate — price kept"
                rows.append(row)
                continue
            row["live"] = cents_to_cad(cents)
            if abs(row["live"] - row["current"]) > 0.005:
                row["status"] = "DRIFT"
            rows.append(row)
    return rows


def build_sku_rows(products_sku: dict, sku_map: dict, inventory: dict) -> list[dict]:
    """One row per sku_to_adelie_id.json entry present in products_sku.json."""
    products = products_sku.get("products", {})
    rows = []
    for sku, entry in sku_map.items():
        if sku.startswith("_"):
            continue
        product = products.get(sku)
        if product is None:
            continue  # mapping for a SKU page that no longer exists
        row = {
            "key": sku,
            "unit": product.get("priceUnit", "?"),
            "current": float(product["startingPriceCAD"]),
            "live": None,
            "status": "ok",
            "note": "",
        }
        if isinstance(entry, str):
            cents = day_rate_cents(inventory.get(entry))
            if entry not in inventory:
                row["status"] = "no-rate"
                row["note"] = "id not in live shop inventory — price kept"
            elif cents is None:
                row["status"] = "no-rate"
                row["note"] = "no/zero daily rate — price kept"
            else:
                row["live"] = cents_to_cad(cents)
        else:
            # Multi-size SKU: anchor startingPriceCAD to the sub-item whose
            # live rate sits closest to the current value (tie -> cheaper).
            candidates = []
            for e in entry:
                cents = day_rate_cents(inventory.get(e.get("id")))
                if cents is not None:
                    candidates.append((cents_to_cad(cents), e.get("label", e["id"])))
            if not candidates:
                row["status"] = "no-rate"
                row["note"] = "no live rates for any mapped sub-item — price kept"
            else:
                live, label = min(
                    candidates, key=lambda c: (abs(c[0] - row["current"]), c[0])
                )
                row["live"] = live
                row["note"] = f"anchor: {label}"
        if row["live"] is not None and abs(row["live"] - row["current"]) > 0.005:
            row["status"] = "DRIFT"
        rows.append(row)
    return rows


def print_rows(title: str, rows: list[dict]) -> None:
    print(f"\n{title}")
    if not rows:
        print("  (no mapped items)")
        return
    key_w = max(len(r["key"]) for r in rows)
    print(f"  {'item':<{key_w}}  {'unit':5}  {'current':>9}  {'live':>9}  "
          f"{'delta':>9}  status")
    for r in rows:
        cur = f"{r['current']:9.2f}"
        if r["live"] is None:
            live, delta = f"{'—':>9}", f"{'—':>9}"
        else:
            live = f"{r['live']:9.2f}"
            delta = f"{r['live'] - r['current']:+9.2f}"
        note = f"  ({r['note']})" if r["note"] else ""
        print(f"  {r['key']:<{key_w}}  {r['unit']:5}  {cur}  {live}  "
              f"{delta}  {r['status']}{note}")


# --------------------------------------------------------------------------
# surgical writes (preserve file formatting byte-for-byte except the number)
# --------------------------------------------------------------------------

def replace_catalog_price(text: str, item_key: str, literal: str) -> str:
    """catalog.json keeps each item object on a single line with "key"
    preceding "priceCAD" — replace the number on that item's line only."""
    pat = re.compile(
        r'("key":\s*"' + re.escape(item_key) + r'"[^\n]*?"priceCAD":\s*)'
        r"(-?\d+(?:\.\d+)?)"
    )
    if len(pat.findall(text)) != 1:
        raise RuntimeError(f"catalog.json: expected exactly one priceCAD for "
                           f"{item_key!r}")
    return pat.sub(lambda m: m.group(1) + literal, text, count=1)


def replace_sku_price(text: str, sku: str, literal: str) -> str:
    """products_sku.json: replace the first startingPriceCAD after the
    product's opening '"<sku>": {' (every product block carries one)."""
    pat = re.compile(
        r'("' + re.escape(sku) + r'":\s*\{.*?"startingPriceCAD":\s*)'
        r"(-?\d+(?:\.\d+)?)",
        re.DOTALL,
    )
    if len(pat.findall(text)) != 1:
        raise RuntimeError(f"products_sku.json: expected exactly one "
                           f"startingPriceCAD for {sku!r}")
    return pat.sub(lambda m: m.group(1) + literal, text, count=1)


def apply_drift(path: Path, drift_rows: list[dict], replace_fn,
                reparse_check, always_decimals: bool = False) -> None:
    """Apply each DRIFT row's live price to `path` via `replace_fn`, then
    re-parse and assert every targeted value actually landed."""
    text = path.read_text(encoding="utf-8")
    for r in drift_rows:
        text = replace_fn(text, r["key"],
                          fmt_price_literal(r["live"], always_decimals))
    doc = json.loads(text)  # raises if an edit corrupted the JSON
    for r in drift_rows:
        got = reparse_check(doc, r["key"])
        if abs(float(got) - r["live"]) > 0.005:
            raise RuntimeError(f"{path.name}: post-write check failed for "
                               f"{r['key']!r} (got {got}, want {r['live']})")
    path.write_text(text, encoding="utf-8")


def catalog_price_of(doc: dict, key: str) -> float:
    for group in doc["groups"]:
        for item in group["items"]:
            if item["key"] == key:
                return item["priceCAD"]
    raise KeyError(key)


def sku_price_of(doc: dict, sku: str) -> float:
    return doc["products"][sku]["startingPriceCAD"]


# --------------------------------------------------------------------------
# main
# --------------------------------------------------------------------------

def main() -> int:
    ap = argparse.ArgumentParser(
        description="Sync planner/SKU prices from the live RentKit shop API."
    )
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true",
                      help="diff local prices vs live rates; exit 1 on drift "
                           "(network errors soft-fail with exit 0)")
    mode.add_argument("--write", action="store_true",
                      help="apply live rates to catalog.json + products_sku.json")
    args = ap.parse_args()

    constants = load_json(CONSTANTS_FILE)
    org_id = constants.get("adelieOrgId")
    if not org_id:
        print("ERROR: no adelieOrgId in _build/site_constants.json", file=sys.stderr)
        return 1
    catalog = load_json(CATALOG_FILE)
    products_sku = load_json(PRODUCTS_SKU_FILE)
    sku_map = load_json(SKU_MAP_FILE)

    # The planner->RentKit id map needs no network — always (re)write it.
    resolved, unmapped = resolve_planner_items(catalog, sku_map)
    write_rentkit_map(resolved, unmapped)
    print(f"wrote {MAP_OUT_FILE.relative_to(HERE.parent)} "
          f"({len(resolved)} mapped, {len(unmapped)} unmapped)")
    if unmapped:
        print("  unmapped planner items (no RentKit mapping — listed in "
              "_unmapped, prices stay manual):")
        for key in unmapped:
            print(f"    - {key}")

    try:
        inventory = fetch_inventory(org_id)
    except (urllib.error.URLError, OSError, RuntimeError,
            json.JSONDecodeError) as e:
        print(f"\nWARNING: could not fetch live RentKit rates ({e}) — "
              "skipping price check (soft-fail).", file=sys.stderr)
        # --check soft-fails so offline builds don't break; --write has
        # nothing it can safely write, so report failure.
        return 0 if args.check else 1

    catalog_rows = build_catalog_rows(catalog, resolved, inventory)
    sku_rows = build_sku_rows(products_sku, sku_map, inventory)
    print_rows("site/planner/catalog.json — planner prices vs live daily rates:",
               catalog_rows)
    print_rows("_build/products_sku.json — startingPriceCAD vs live daily rates:",
               sku_rows)

    catalog_drift = [r for r in catalog_rows if r["status"] == "DRIFT"]
    sku_drift = [r for r in sku_rows if r["status"] == "DRIFT"]
    drift_count = len(catalog_drift) + len(sku_drift)

    if args.check:
        if drift_count:
            print(f"\nDRIFT — {drift_count} price(s) differ from live RentKit "
                  "rates. Apply with: python3 _build/sync_planner_catalog.py --write")
            return 1
        print("\nCLEAN — all mapped prices match live RentKit rates.")
        return 0

    # --write
    if not drift_count:
        print("\nNo price drift — nothing to write.")
        return 0
    if catalog_drift:
        apply_drift(CATALOG_FILE, catalog_drift, replace_catalog_price,
                    catalog_price_of)
        for r in catalog_drift:
            print(f"updated site/planner/catalog.json: {r['key']} "
                  f"{fmt_price_literal(r['current'])} -> "
                  f"{fmt_price_literal(r['live'])}")
    if sku_drift:
        apply_drift(PRODUCTS_SKU_FILE, sku_drift, replace_sku_price,
                    sku_price_of, always_decimals=True)
        for r in sku_drift:
            print(f"updated _build/products_sku.json: {r['key']} "
                  f"{fmt_price_literal(r['current'], True)} -> "
                  f"{fmt_price_literal(r['live'], True)}")
    print("\nREMINDERS:")
    print("  - bump the ?v= cache-bust on the planner.js / planner.css "
          "includes in site/event-layout-planner-embed.html")
    if sku_drift:
        print("  - products_sku.json prose (metaDescription / priceRange / "
              "bullets) may still quote the old price — review, then "
          "regenerate pages: python3 _build/generate_sku_pages.py --all")
    return 0


if __name__ == "__main__":
    sys.exit(main())
