"""
Forever Party Rentals — idempotent nav/footer injector for hand-authored HTML.

Walks the listed .html files and inserts (or replaces) the static nav and
footer between sentinel comments:

  <!-- NAV:START -->...<!-- NAV:END -->     placed as first child of <body>
  <!-- FOOTER:START -->...<!-- FOOTER:END -->   placed before the trailing
                                                shared.js script tag

First run inserts the markers in the correct positions. Subsequent runs are
pure replacements between the markers — fully idempotent.

This script is intentionally NOT responsible for cache-bust version bumps.
Bump shared.js / shared.css versions with a separate sed pass:

  find site/ _build/ -type f \\( -name '*.html' -o -name '*.j2' \\) \\
       -exec sed -i -E 's|shared\\.(js|css)\\?v=OLD|shared.\\1?v=NEW|g' {} +

Decoupling keeps each concern (partial injection vs. cache-busting) reviewable
in isolation and prevents accidental version downgrades when re-running.

Generated pages (city / product / SKU / christmas / package) do NOT go through
this script — they get the same HTML via Jinja {% include %} in their
templates and the generator regenerates them. Only hand-authored files in
site/*.html and site/blog/*.html are touched here.

Usage:
  python3 _build/apply_partials.py site/contact.html site/index.html ...
  python3 _build/apply_partials.py --hand-authored
  python3 _build/apply_partials.py --blog
  python3 _build/apply_partials.py --all                     # both groups
  python3 _build/apply_partials.py --dry-run --all           # preview only

No Netlify or third-party dependencies. Python 3.8+ stdlib + Jinja2 (project dep).
"""
from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

# Repo-relative import of the renderer. We're already inside _build/.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from render_partials import render_nav, render_footer  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
SITE_DIR = REPO_ROOT / "site-v3"

# Hand-authored pages that need nav/footer (excludes generated output).
HAND_AUTHORED = [
    "index.html",
    "contact.html",
    "faq.html",
    "corporate.html",
    "service-areas.html",
    "packages.html",
    "privacy.html",
    "rentals.html",
    "checkout.html",
    "thank-you.html",
    "404.html",
    "reviews.html",
    "tents.html",
    "chairs.html",
    "tables.html",
    "dance-floor.html",
    "battery-power-stations.html",
    "starlink-rentals.html",
    "projector-rentals.html",
    "christmas-lights.html",
    "christmas-light-installation-lower-mainland.html",
    "marquee-tent-rental-lowermainland-surrey-langley-vancouver.html",
    # Public-facing hub page for the Event Layout Planner. The bare embed
    # surface (event-layout-planner-embed.html) is intentionally NOT listed
    # here — it has no nav/footer by design.
    "event-layout-planner.html",
    # Planner ecosystem pages (Phase 3): calculator, spacing reference,
    # partner-embed pitch, and the three use-case landing pages.
    "tent-size-calculator.html",
    "event-spacing-guide.html",
    "embed-the-planner.html",
    "wedding-tent-layout-planner.html",
    "backyard-party-layout-planner.html",
    "corporate-event-layout-planner.html",
    # Capacity-guide landing pages — restored from 301s back to standalone
    # informational pages. Historical URLs that pulled position 5–6 on
    # high-volume informational queries; now serve a direct Q&A answer with
    # FAQPage + Speakable schema and a CTA to the matching SKU page.
    "how-many-people-fit-at-a-6ft-rectangular-table.html",
    "how-many-people-fit-at-round-tables.html",
    # Birthday-demand landing page (June 2026 — "birthday party rentals",
    # 196 impr/28d at pos 18.5, previously no owner page).
    "birthday-party-rentals.html",
    # One product-*.html file that is NOT in products_sku.json and so doesn't get
    # regenerated by generate_sku_pages.py — hand-authored, lives alongside the
    # generated SKU pages. (product-marquee-tent-20x30 moved into products_sku.json;
    # listing it here too made apply_partials inject a second nav on top of the
    # generator's inline one.)
    "product-banquet-table-8ft.html",
    # Standalone hub + carnival pages (July 2026): hand-authored, carry the
    # NAV/FOOTER sentinels but were missing from this list, so their navs
    # drifted whenever the partials changed.
    "event-rentals.html",
    "wedding-rentals.html",
    "carnival-games.html",
    "carnival-games-bundle-2.html",
    "carnival-games-bundle-4.html",
    "product-bottle-knockdown.html",
    "product-balloon-darts.html",
    "product-cup-toss.html",
    "product-ring-toss.html",
    "blog/index.html",
]

# Sentinel markers — content between them gets replaced on every run.
NAV_START = "<!-- NAV:START -->"
NAV_END = "<!-- NAV:END -->"
FOOTER_START = "<!-- FOOTER:START -->"
FOOTER_END = "<!-- FOOTER:END -->"


def _apply_nav(html: str, nav_html: str) -> str:
    block = f"{NAV_START}\n{nav_html}\n{NAV_END}"

    # Re-run case: replace whatever sits between the markers, preserving them.
    if NAV_START in html and NAV_END in html:
        return re.sub(
            re.escape(NAV_START) + r".*?" + re.escape(NAV_END),
            block,
            html,
            count=1,
            flags=re.DOTALL,
        )

    # First-run case: insert immediately after <body[ ...]>.
    body_match = re.search(r"<body\b[^>]*>", html)
    if not body_match:
        raise SystemExit("No <body> tag found; cannot insert nav.")
    insert_pos = body_match.end()
    return html[:insert_pos] + "\n" + block + html[insert_pos:]


def _apply_footer(html: str, footer_html: str) -> str:
    block = f"{FOOTER_START}\n{footer_html}\n{FOOTER_END}"

    if FOOTER_START in html and FOOTER_END in html:
        return re.sub(
            re.escape(FOOTER_START) + r".*?" + re.escape(FOOTER_END),
            block,
            html,
            count=1,
            flags=re.DOTALL,
        )

    # First-run: insert immediately before the trailing shared.js script tag.
    # Both `shared.js` and `../shared.js` accepted.
    script_re = re.compile(
        r"<script\s+src=\"(?:\.\./)?shared\.js\?v=\d+\"\s*></script>",
        re.IGNORECASE,
    )
    m = script_re.search(html)
    if not m:
        raise SystemExit(
            "No <script src=\".../shared.js?v=N\"></script> found; cannot insert footer."
        )
    return html[:m.start()] + block + "\n" + html[m.start():]


def process_file(path: Path, nav_html: str, footer_html: str, dry_run: bool = False) -> bool:
    """Returns True if the file was changed."""
    original = path.read_text(encoding="utf-8")
    updated = _apply_nav(original, nav_html)
    updated = _apply_footer(updated, footer_html)
    if updated == original:
        return False
    if not dry_run:
        path.write_text(updated, encoding="utf-8")
    return True


def collect_targets(args: argparse.Namespace) -> list[Path]:
    targets: list[Path] = []
    if args.all or args.hand_authored:
        targets.extend(SITE_DIR / rel for rel in HAND_AUTHORED)
    if args.all or args.blog:
        blog_dir = SITE_DIR / "blog"
        # Glob includes _template.html intentionally — future posts inherit the markers.
        blog_files = sorted(blog_dir.glob("*.html"))
        # Hand-authored set already includes blog/index.html; avoid duplicates.
        already = {SITE_DIR / "blog" / "index.html"}
        targets.extend(p for p in blog_files if p not in already)
    targets.extend(Path(p) for p in args.paths)
    # De-duplicate while preserving order.
    seen = set()
    deduped: list[Path] = []
    for t in targets:
        rp = t.resolve()
        if rp in seen:
            continue
        seen.add(rp)
        deduped.append(t)
    return deduped


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("paths", nargs="*", help="Specific files to process")
    ap.add_argument("--hand-authored", action="store_true", help="Process the 19 hand-authored pages")
    ap.add_argument("--blog", action="store_true", help="Process site/blog/*.html")
    ap.add_argument("--all", action="store_true", help="Process both groups")
    ap.add_argument("--dry-run", action="store_true", help="Show what would change, don't write")
    args = ap.parse_args()

    if not (args.paths or args.hand_authored or args.blog or args.all):
        ap.print_help()
        return 1

    targets = collect_targets(args)

    # Sanity-check the blog set against site/blog/posts.json (the manifest).
    # Catches accidentally-deleted post files OR posts.json drift. Fail loud.
    if args.all or args.blog:
        manifest_path = SITE_DIR / "blog" / "posts.json"
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        expected_slugs = {p["slug"] for p in manifest["posts"]}
        on_disk = {p.stem for p in (SITE_DIR / "blog").glob("*.html")
                   if p.stem not in {"index", "_template"}}
        missing = expected_slugs - on_disk
        orphaned = on_disk - expected_slugs
        if missing:
            print(f"ERROR: posts.json lists {sorted(missing)} but those .html files are missing.")
            return 4
        if orphaned:
            print(f"ERROR: site/blog/ has {sorted(orphaned)}.html with no entry in posts.json.")
            return 4

    nav_html = render_nav()
    footer_html = render_footer()

    print(f"Targets: {len(targets)} file(s)")
    changed = unchanged = missing = 0
    for path in targets:
        if not path.exists():
            print(f"  MISSING: {path}")
            missing += 1
            continue
        try:
            if process_file(path, nav_html, footer_html, dry_run=args.dry_run):
                print(f"  {'would update' if args.dry_run else 'updated '} {path.relative_to(REPO_ROOT)}")
                changed += 1
            else:
                print(f"  unchanged  {path.relative_to(REPO_ROOT)}")
                unchanged += 1
        except SystemExit as e:
            print(f"  ERROR    {path.relative_to(REPO_ROOT)}: {e}")
            return 2

    suffix = " (dry-run)" if args.dry_run else ""
    print(f"\nDone{suffix}: {changed} changed, {unchanged} unchanged, {missing} missing.")
    return 0 if missing == 0 else 3


if __name__ == "__main__":
    sys.exit(main())
